### ISSUE TITLE
无法查询地图成绩

### ISSUE THREAD

**Issue by ElizaKzi** [Yuri-YuzuChaN/osuv2#1]
![6TY{_)ML5TCJ@S2)CZ4D1AO](https://user-images.githubusercontent.com/63360445/172060300-8a2af976-09bc-4958-bed1-d23bd1f56175.png)
![YQ@ CJHMOAVN(69~78P5BR3](https://user-images.githubusercontent.com/63360445/172060312-69335fa6-a46c-4030-bbe8-2ad6d5540676.png)

**Comment by Yuri-YuzuChaN** [comment]
可能自己网络问题或者小夜下载站出问题

**Comment by ElizaKzi** [comment]
> 可能自己的网络问题或小夜下载站出问题

我的服务器在香港，是因为这个吗？
