### ISSUE TITLE
osuhelp指令报错

### ISSUE THREAD

**Issue by ElizaKzi** [Yuri-YuzuChaN/osuv2#6]
![image](https://user-images.githubusercontent.com/63360445/227183189-f1cfb70a-c90f-419c-865c-289231625ae2.png)

![image](https://user-images.githubusercontent.com/63360445/227183036-eae2ba65-a6b8-4792-8c80-03d6f70b0d64.png)

**Comment by Yuri-YuzuChaN** [comment]
已修复 https://github.com/Yuri-YuzuChaN/osuv2/commit/4dcc32295ba91763b3eb1b3e5a1350a46259ba01
